// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8FYC97TIGiWklm-DTngKJ6jN-KngrR78',
    appId: '1:1072245471329:web:888995441a1ca8a2685220',
    messagingSenderId: '1072245471329',
    projectId: 'pingolearn-ecommerce-app',
    authDomain: 'pingolearn-ecommerce-app.firebaseapp.com',
    storageBucket: 'pingolearn-ecommerce-app.appspot.com',
    measurementId: 'G-FYQ8MHV1MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymHb9_D_hHfQ5GAgtcTnDf1hN2QLNfBE',
    appId: '1:1072245471329:android:80747710c10834c4685220',
    messagingSenderId: '1072245471329',
    projectId: 'pingolearn-ecommerce-app',
    storageBucket: 'pingolearn-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgCudrP2jX7b3GNQEdzHIf8QKNZDYLGEQ',
    appId: '1:1072245471329:ios:2c046d7febb13d4f685220',
    messagingSenderId: '1072245471329',
    projectId: 'pingolearn-ecommerce-app',
    storageBucket: 'pingolearn-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.pingolearnEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgCudrP2jX7b3GNQEdzHIf8QKNZDYLGEQ',
    appId: '1:1072245471329:ios:2c046d7febb13d4f685220',
    messagingSenderId: '1072245471329',
    projectId: 'pingolearn-ecommerce-app',
    storageBucket: 'pingolearn-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.pingolearnEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8FYC97TIGiWklm-DTngKJ6jN-KngrR78',
    appId: '1:1072245471329:web:b02c857c7de35764685220',
    messagingSenderId: '1072245471329',
    projectId: 'pingolearn-ecommerce-app',
    authDomain: 'pingolearn-ecommerce-app.firebaseapp.com',
    storageBucket: 'pingolearn-ecommerce-app.appspot.com',
    measurementId: 'G-C62CEEH7W0',
  );
}
